### ISSUE TITLE
Jumps around in Firefox

### ISSUE THREAD

**Issue by akaihola** [akaihola/mmoinsweeper#11]
From @samoylovfp:
>In Firefox the viewport sometimes starts to jump around, I'll try to debug this.

**Comment by akaihola** [comment]
@samoylovfp any clues on when this happens?

I'm playing on Firefox on the laptop as well, and I haven't yet seen this.

**Comment by Sorseg** [comment]
I cannot seem to replicate it anymore. I wonder if it was something wrong with my firefox
